Re-export useSignals in @preact/signals-react
preactjs/signals pull request #474
Opened 2023-12-22 06:30 UTC by JonAbrams

Fixes #473

2024-01-22 21:35 UTC, andrewiggins requested changes
Thanks! Let's adjust the changeset release and get this out :)

2024-01-22 21:35 UTC, andrewiggins commented on .changeset/wild-deers-leave.md
> +"@preact/signals-react": minor
Let's make this a `patch` change since this a bug fix with no new feature introductions

2024-01-22 21:37 UTC, andrewiggins commented
Actually, just saw that the Readme was updated. Let's roll with that for now. Thanks for opening this though.

2024-01-22 21:37 UTC, closed without merging

2024-01-23 17:38 UTC, rschristian commented
@andrewiggins `react-transform` doesn't re-export core though, do we want this?

```js
import { signal, effect } from '@preact/signals-react';
import { useSignals, useSignal } from '@preact/signals-react-runtime';
```

I'm not super in love with this myself.